List<String> months = [
  "Jan",
  "Feb",
  "Feb",
  "Mar",
  "Apr",
  "Apr",
  "May",
  "May",
  "Jul",
  "Jul",
  "Aug",
  "Aug",
  "Sep",
  "Nov",
  "Nov",
];
List<String> days = [
  "23",
  "7",
  "22",
  "20",
  "4",
  "27",
  "4",
  "29",
  "10",
  "14",
  "21",
  "28",
  "5",
  "6",
  "13",
];
List<String> content = [
  "Mentoring organizations can begin submitting applications to Google",
  "Mentoring organization application deadline",
  "List of accepted mentoring organizations published",
  "GSoC contributor application period begins",
  "GSoC contributor application deadline",
  "GSoC contributor proposal rankings due from Org Admins",
  "Accepted GSoC contributor projects announced",
  "Coding officially begins!                      ",
  "Mentors and GSoC contributors can begin submitting midterm evaluations",
  "Midterm evaluation deadline (standard coding period)",
  "Final week: GSoC contributors submit their final work product and their final mentor evaluation",
  "Mentors submit final GSoC contributor evaluations",
  "Initial results of Google Summer of Code 2023 announced",
  "Final date for all GSoC contributors to submit their final work product and final evaluation",
  "Final date for mentors to submit evaluations for GSoC contributor projects with extended deadlines",
];
